[package]
name = "radiosity"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "22.0"
anyhow = "1.0.95"
thiserror = "2.0.11"
pollster = "0.3"
bytemuck = { version = "1.21.0", features = ["derive"] }
